### PR TITLE
[CI] Add ci pipeline docs

### LINKED ISSUE #9262: Add documentation about CI pipelines run for every PR and on a daily basis
Add documentation about the CI pipelines that are defined for this repository into the CONTRIBUTING guide.

- CI pipelines that are being run for every Pull Request and merge to main or backport branches.:
    - Which Elastic stack versions are run for every package
    - How they can be re-triggered (github comments).
    - Which packages are being tested in each PR.
    - Add links to Buildkite jobs.
    - Definitions:
        - [Main pipeline](https://github.com/elastic/integrations/blob/22893c20773fc37e2086c89c59b71fb9fe8f3512/.buildkite/pipeline.yml)
- CI pipelines that are being run on a daily basis:
    - Which pipelines are triggered (currently, for Serverless and local Elastic stacks)
    - Which Elastic stack versions are tested in those pipelines triggered.
    - Which Serverless projects are tested.
    - Exceptions in Serverless projects (e.g. system test are not executed or geoip databases).
    - Add links to Buildkite jobs.
    - Definitions:
        - [Schedule daily job](https://github.com/elastic/integrations/blob/22893c20773fc37e2086c89c59b71fb9fe8f3512/.buildkite/pipeline.schedule-daily.yml)
        - [Serverless job](https://github.com/elastic/integrations/blob/22893c20773fc37e2086c89c59b71fb9fe8f3512/.buildkite/pipeline.serverless.yml)

### PR DESCRIPTION
**Pull request by mrodm**
## Proposed commit message

Added documentation about the different CI pipelines available in this repository.

## Related issues

- Closes #9262

### CODE REVIEW

File: .buildkite/scripts/common.sh [hunk 1]
```diff
@@ -692,7 +692,7 @@ is_pr_affected() {
 
     echo "[${package}] git-diff: check non-package files"
     commit_merge=$(git merge-base "${from}" "${to}")
-    if git diff --name-only "${commit_merge}" "${to}" | grep -E -v '^(packages/|.github/CODEOWNERS|docs/)' ; then
+    if git diff --name-only "${commit_merge}" "${to}" | grep -E -v '^(packages/|.github/CODEOWNERS|README.md|docs/|.buildkite/)' ; then
```
Comment (mrodm) [inline .buildkite/scripts/common.sh]: This adds an exclusion for the README.md at the root of the working copy. 
WDYT ? @jsoriano

Here there is a build with an example of a package that updates another README.md file and the package is tested:
https://buildkite.com/elastic/integrations/builds/13619

File: .buildkite/scripts/common.sh [hunk 2]
```diff
@@ -692,7 +692,7 @@ is_pr_affected() {
 
     echo "[${package}] git-diff: check non-package files"
     commit_merge=$(git merge-base "${from}" "${to}")
-    if git diff --name-only "${commit_merge}" "${to}" | grep -E -v '^(packages/|.github/CODEOWNERS|docs/)' ; then
+    if git diff --name-only "${commit_merge}" "${to}" | grep -E -v '^(packages/|.github/CODEOWNERS|README.md|docs/)' ; then
```
Comment (mrodm) [inline .buildkite/scripts/common.sh:695]: This adds an exclusion for the README.md at the root of the working copy. 
WDYT ? @jsoriano

Here there is a build with an example of a package that updates another README.md file and the package is tested:
https://buildkite.com/elastic/integrations/builds/13619

File: docs/ci_pipelines.md [hunk 3]
```diff
@@ -0,0 +1,154 @@
...
+- **FORCE_CHECK_ALL**: If `true`, this forces the CI to check all packages even if those packages have no file updated/added/deleted. Default: `false`.
+- **STACK_VERSION**: Force the CI steps to spin up a specific Elastic stack version to run the tests. Default: unset.
+- **PUBLISH_COVERAGE_REPORTS**: If `true`, it enables reporting coverage reports.
+Currently, it is just set for the build triggered with the current major Elastic stack from the daily job. Default: `false`.
+
+These environment variables can be defined in different locations:
+- In the [global `env` section](https://github.com/elastic/integrations/blob/5276ef63712f8f2311818770881688870e8422fe/.buildkite/pipeline.yml#L2).
+- In the case of the scheduled daily job here:
+    - [Running tests with previous major Elastic stack](https://github.com/elastic/integrations/blob/5276ef63712f8f2311818770881688870e8422fe/.buildkite/pipeline.schedule-daily.yml#L21).
+    - [Running tests with current major Elastic stack](https://github.com/elastic/integrations/blob/d6d99792b90838d18844f6df9343bc5f16130666/.buildkite/pipeline.schedule-daily.yml#L32).
```
Comment (jsoriano) [inline docs/ci_pipelines.md:32]: Wdyt about referencing main instead of specific commits? Given that they live in the same repository.
```suggestion
- In the [global `env` section](https://github.com/elastic/integrations/blob/main/.buildkite/pipeline.yml#L2).
- In the case of the scheduled daily job here:
    - [Running tests with previous major Elastic stack](https://github.com/elastic/integrations/blob/main/.buildkite/pipeline.schedule-daily.yml#L21).
    - [Running tests with current major Elastic stack](https://github.com/elastic/integrations/blob/main/.buildkite/pipeline.schedule-daily.yml#L32).
```

File: docs/ci_pipelines.md [hunk 4]
```diff
@@ -0,0 +1,154 @@
...
+
+More details about this CI pipeline:
+
+- Builds running in a Pull Request are canceled if a new commit is pushed to the PR branch.
+- Builds running from `main` or `backport-*` branches are finished even if new commits are merged.
+- As part of the Pull Requests, there are some benchmark files created and this data is pushed to the PR as a comment.
+- This CI pipeline tries to test the minimum packages possible::
+    - In the Pull Request context, it is checked the files modified/added/deleted in the given PR:
+        - Those packages with changes (`packages/*`) will be added to the list of packages to be tested.
+        - If files outside `packages` folder are updated (e.g. `go.mod` , `.buildkite/*`), all packages are going to be tested. There are some exceptions to this, for instance the `.github/CODEOWNERS` file or `.docs/` folder ([files excluded](https://github.com/elastic/integrations/blob/376fc891a1e6c662b4ef1897b118044faf51e7bf/.buildkite/scripts/common.sh#L695)).
```
Comment (jsoriano) [inline docs/ci_pipelines.md:42]:
```suggestion
        - If files outside `packages` folder are updated (e.g. `go.mod` , `.buildkite/*`), all packages are going to be tested. There are some exceptions to this, for instance the `.github/CODEOWNERS` file or `.docs/` folder ([files excluded](https://github.com/elastic/integrations/blob/main/.buildkite/scripts/common.sh#L695)).
```

**Review by jsoriano — APPROVED** [review]
:+1:

File: docs/ci_pipelines.md (hunk 3 above)
Comment (mrodm) [reply docs/ci_pipelines.md:32]: As I'm linking to specific lines in the files in most (or all) of the links, I think these links could be outdated easily at any time (and not updated in these docs) if they reference main... 

I would keep it referencing to commit.

**Review by kpollich — APPROVED** [review]
