### PR TITLE
Report packages failing in daily CI jobs

### LINKED ISSUE #6071: Improve visibility on failures in daily job
We have a ~~[daily job](https://fleet-ci.elastic.co/job/Ingest-manager/job/integrations-daily/)~~ [daily job](https://buildkite.com/elastic/integrations-schedule-daily) that tests all integrations with the latest snapshot version of the stack. Failures on this job are only reported to a Slack Channel, but this has been failing for some time, so it has been relying on manually checking the health of the job.

Define a better visibility strategy for this job, so we can early detect issues there, and notify the affected teams.

Some ideas:
* Automatically create an issue when an integration fails on this job, assigned to the team maintaining the package.
* Include the failing integrations in the notifications in slack or other means.

### PR DESCRIPTION
**Pull request by mrodm**
## Proposed commit message

Report packages failing in daily CI jobs creating GitHub issues for each test failing present in the xUnit files generated by elastic-package.

Example of issues created with this new tool:
- https://github.com/elastic/integrations/issues/10250
- https://github.com/elastic/integrations/issues/10332
- https://github.com/elastic/integrations/issues/10336 

## Author's Checklist

- [x] Ensure github cli command is installed
- [x] Check create new issues
- [x] Check update issues with new Buildkite builds
- [x] Add an environment variable (and a default value) to report maximum N issues
- [x] Remove TODOs before merging
- [x] Remove changes in `.buildkite/scripts/common.sh`
- [x] Remove changes in `elastic_package_registry` package

## Related issues

- Closes #6071

### CODE REVIEW

File: dev/testsreporter/testsreporter.go [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+
+	aReporter := reporter{
+		ghCli:            ghCli,
+		maxPreviousLinks: maxPreviousLinks,
+	}
+
+	if len(packageErrors) > maxTestsReported {
+		fmt.Printf("Skip creating GitHub issues, hit the maximum number (%d) of tests to be reported. Total failing tests: %d.\n", maxTestsReported, len(packageErrors))
+		return nil
+	}
```
Comment (mrodm) [inline dev/testsreporter/testsreporter.go:49]: If there are more than `maxTestsReported` tests failing, it will not create any issues this tool.

This value can be tuned by settings the environment variable `CI_MAX_TESTS_REPORTED`.

File: dev/testsreporter/format.go [hunk 2]
```diff
@@ -0,0 +1,121 @@
...
+	// TODO: remove ignore statement
+	return fmt.Sprintf("%s - IGNORE testing", r.result.String())
+}
+
+func (r ResultsFormatter) Owners() []string {
+	return r.result.Teams
+}
+
+func (r ResultsFormatter) Summary() string {
+	var sb strings.Builder
```
Comment (jsoriano) [inline dev/testsreporter/format.go:29]: Nit. For this case maybe we can use a template, it would be easier to read.

File: dev/testsreporter/format.go [hunk 3]
```diff
@@ -0,0 +1,121 @@
...
+			sb.WriteString(owner)
+			sb.WriteString("\n")
+		}
+	}
+
+	return sb.String()
+}
+
+func (r ResultsFormatter) Description() string {
+	var sb strings.Builder
```
Comment (jsoriano) [inline dev/testsreporter/format.go:64]: Nit. Also here we could maybe use a template.

File: dev/testsreporter/github.go [hunk 4]
```diff
@@ -0,0 +1,172 @@
...
+		runner: runner,
+	}
+}
+
+func (g *GhCli) Exists(ctx context.Context, issue *GithubIssue, open bool) (bool, *GithubIssue, error) {
+	stateIssue := "open"
+	if !open {
+		stateIssue = "closed"
+	}
+	stdout, stderr, err := g.runner.Exec(ctx,
```
Comment (jsoriano) [inline dev/testsreporter/github.go:68]: Have you considered to use some SDK for the REST API like [github.com/google/go-github](https://pkg.go.dev/github.com/google/go-github/v62/github#SearchService.Issues) instead of using the command?

File: go.mod [hunk 5]
```diff
@@ -12,6 +13,7 @@ require (
 	github.com/stretchr/testify v1.9.0
 	golang.org/x/tools v0.22.0
 	gopkg.in/yaml.v2 v2.4.0
+	gopkg.in/yaml.v3 v3.0.1
```
Comment (jsoriano) [inline go.mod:16]: Should we migrate everything to v3? Is there any reason to use both versions?

**Review by jsoriano — APPROVED** [review]
Nice, and great test coverage :+1: Added a couple of suggestions, but feel free to reject them.

File: go.mod (hunk 5 above)
Comment (mrodm) [reply go.mod:16]: yaml.v2 is used in `import-beats` package (`dev/import-beats`), not sure how to test this package, but I could open a different PR to update that dependency in all packages.

Comment (mrodm) [reply go.mod:16]: PR created https://github.com/elastic/integrations/pull/10325

File: dev/testsreporter/format.go (hunk 2 above)
Comment (mrodm) [reply dev/testsreporter/format.go]: Sure, updated in the latest changesets for both the summary and the description.
Thanks for the suggestion!

File: dev/testsreporter/github.go (hunk 4 above)
Comment (mrodm) [reply dev/testsreporter/github.go:68]: I just used the official library/tool from github for the `gh` tool. I guess it could be kept as it is, and this could be replaced in the future if we see there is any issue or errors because of using the CLI.

**Comment by mrodm** [comment]
Merging since CI failure are unrelated to the changes on this PR.
